# Generated by Django 5.1.3 on 2024-12-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='published_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
