# Generated by Django 5.1.3 on 2024-12-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_alter_books_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='published_date',
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.CharField(default='21234324326', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='quantity',
            field=models.PositiveIntegerField(default=21),
            preserve_default=False,
        ),
    ]
