# Generated by Django 5.1.3 on 2024-12-11 09:11

import books_app.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_books_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='availability',
            field=models.CharField(choices=[('In stock', 'In stock'), ('Out of stock', 'Out of stock'), ('On sale', 'On sale'), ('New', 'New')], default='New', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='format',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Downloadable', 'Downloadable'), ('External', 'External')], default='new', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='books_pdf/', validators=[books_app.validators.validate_file_type]),
        ),
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.AlterField(
            model_name='books',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_app.author'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_app.books')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='books', to='books_app.category'),
        ),
    ]
