# Generated by Django 5.1.3 on 2024-12-18 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_remove_books_published_date_books_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(choices=[('New', 'New'), ('Sent', 'Sent'), ('Canceled', 'Canceled')], default='New', max_length=250)),
                ('quantity', models.PositiveIntegerField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_orders', to='books_app.books')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_status', models.CharField(choices=[('Saved', 'Saved'), ('Canceled', 'Canceled')], default='Saved', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('orders', models.ManyToManyField(blank=True, related_name='carts', to='books_app.orderitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
